-- Todos los municipios de Colombia (DIVIPOLA del DANE) con su departamento.
-- Spec: specs/2026-10-06-etiquetas-ciudades-busqueda/plan.md, 1e.
-- GENERADO por scripts/build-cities-migration.ts desde supabase/data/divipola.csv
-- (1122 filas). No editar a mano: corregir el script y regenerar.
--
-- Las 3 ciudades que ya existían (Bogotá, Medellín, Barranquilla) conservan id y slug:
-- se completan por slug y el insert las salta. Idempotente.

alter table cities
  add column if not exists department text,
  add column if not exists dane_code  text unique;

-- Un solo statement con CTE (sin tabla temporal): el SQL Editor de Supabase no conserva una
-- tabla temporal entre statements. El update completa las 3 ciudades existentes; el insert
-- choca con sus slugs y las salta.
with divipola (dane_code, name, department, slug) as (
  values
    ('05001', 'Medellín', 'Antioquia', 'medellin'),
    ('05002', 'Abejorral', 'Antioquia', 'abejorral'),
    ('05004', 'Abriaquí', 'Antioquia', 'abriaqui'),
    ('05021', 'Alejandría', 'Antioquia', 'alejandria'),
    ('05030', 'Amagá', 'Antioquia', 'amaga'),
    ('05031', 'Amalfi', 'Antioquia', 'amalfi'),
    ('05034', 'Andes', 'Antioquia', 'andes'),
    ('05036', 'Angelópolis', 'Antioquia', 'angelopolis'),
    ('05038', 'Angostura', 'Antioquia', 'angostura'),
    ('05040', 'Anorí', 'Antioquia', 'anori'),
    ('05042', 'Santa Fé de Antioquia', 'Antioquia', 'santa-fe-de-antioquia'),
    ('05044', 'Anzá', 'Antioquia', 'anza'),
    ('05045', 'Apartadó', 'Antioquia', 'apartado'),
    ('05051', 'Arboletes', 'Antioquia', 'arboletes'),
    ('05055', 'Argelia', 'Antioquia', 'argelia-antioquia'),
    ('05059', 'Armenia', 'Antioquia', 'armenia-antioquia'),
    ('05079', 'Barbosa', 'Antioquia', 'barbosa-antioquia'),
    ('05086', 'Belmira', 'Antioquia', 'belmira'),
    ('05088', 'Bello', 'Antioquia', 'bello'),
    ('05091', 'Betania', 'Antioquia', 'betania'),
    ('05093', 'Betulia', 'Antioquia', 'betulia-antioquia'),
    ('05101', 'Ciudad Bolívar', 'Antioquia', 'ciudad-bolivar'),
    ('05107', 'Briceño', 'Antioquia', 'briceno-antioquia'),
    ('05113', 'Buriticá', 'Antioquia', 'buritica'),
    ('05120', 'Cáceres', 'Antioquia', 'caceres'),
    ('05125', 'Caicedo', 'Antioquia', 'caicedo'),
    ('05129', 'Caldas', 'Antioquia', 'caldas-antioquia'),
    ('05134', 'Campamento', 'Antioquia', 'campamento'),
    ('05138', 'Cañasgordas', 'Antioquia', 'canasgordas'),
    ('05142', 'Caracolí', 'Antioquia', 'caracoli'),
    ('05145', 'Caramanta', 'Antioquia', 'caramanta'),
    ('05147', 'Carepa', 'Antioquia', 'carepa'),
    ('05148', 'El Carmen de Viboral', 'Antioquia', 'el-carmen-de-viboral'),
    ('05150', 'Carolina', 'Antioquia', 'carolina'),
    ('05154', 'Caucasia', 'Antioquia', 'caucasia'),
    ('05172', 'Chigorodó', 'Antioquia', 'chigorodo'),
    ('05190', 'Cisneros', 'Antioquia', 'cisneros'),
    ('05197', 'Cocorná', 'Antioquia', 'cocorna'),
    ('05206', 'Concepción', 'Antioquia', 'concepcion-antioquia'),
    ('05209', 'Concordia', 'Antioquia', 'concordia-antioquia'),
    ('05212', 'Copacabana', 'Antioquia', 'copacabana'),
    ('05234', 'Dabeiba', 'Antioquia', 'dabeiba'),
    ('05237', 'Donmatías', 'Antioquia', 'donmatias'),
    ('05240', 'Ebéjico', 'Antioquia', 'ebejico'),
    ('05250', 'El Bagre', 'Antioquia', 'el-bagre'),
    ('05264', 'Entrerríos', 'Antioquia', 'entrerrios'),
    ('05266', 'Envigado', 'Antioquia', 'envigado'),
    ('05282', 'Fredonia', 'Antioquia', 'fredonia'),
    ('05284', 'Frontino', 'Antioquia', 'frontino'),
    ('05306', 'Giraldo', 'Antioquia', 'giraldo'),
    ('05308', 'Girardota', 'Antioquia', 'girardota'),
    ('05310', 'Gómez Plata', 'Antioquia', 'gomez-plata'),
    ('05313', 'Granada', 'Antioquia', 'granada-antioquia'),
    ('05315', 'Guadalupe', 'Antioquia', 'guadalupe-antioquia'),
    ('05318', 'Guarne', 'Antioquia', 'guarne'),
    ('05321', 'Guatapé', 'Antioquia', 'guatape'),
    ('05347', 'Heliconia', 'Antioquia', 'heliconia'),
    ('05353', 'Hispania', 'Antioquia', 'hispania'),
    ('05360', 'Itagüí', 'Antioquia', 'itagui'),
    ('05361', 'Ituango', 'Antioquia', 'ituango'),
    ('05364', 'Jardín', 'Antioquia', 'jardin'),
    ('05368', 'Jericó', 'Antioquia', 'jerico-antioquia'),
    ('05376', 'La Ceja', 'Antioquia', 'la-ceja'),
    ('05380', 'La Estrella', 'Antioquia', 'la-estrella'),
    ('05390', 'La Pintada', 'Antioquia', 'la-pintada'),
    ('05400', 'La Unión', 'Antioquia', 'la-union-antioquia'),
    ('05411', 'Liborina', 'Antioquia', 'liborina'),
    ('05425', 'Maceo', 'Antioquia', 'maceo'),
    ('05440', 'Marinilla', 'Antioquia', 'marinilla'),
    ('05467', 'Montebello', 'Antioquia', 'montebello'),
    ('05475', 'Murindó', 'Antioquia', 'murindo'),
    ('05480', 'Mutatá', 'Antioquia', 'mutata'),
    ('05483', 'Nariño', 'Antioquia', 'narino-antioquia'),
    ('05490', 'Necoclí', 'Antioquia', 'necocli'),
    ('05495', 'Nechí', 'Antioquia', 'nechi'),
    ('05501', 'Olaya', 'Antioquia', 'olaya'),
    ('05541', 'Peñol', 'Antioquia', 'penol'),
    ('05543', 'Peque', 'Antioquia', 'peque'),
    ('05576', 'Pueblorrico', 'Antioquia', 'pueblorrico'),
    ('05579', 'Puerto Berrío', 'Antioquia', 'puerto-berrio'),
    ('05585', 'Puerto Nare', 'Antioquia', 'puerto-nare'),
    ('05591', 'Puerto Triunfo', 'Antioquia', 'puerto-triunfo'),
    ('05604', 'Remedios', 'Antioquia', 'remedios'),
    ('05607', 'Retiro', 'Antioquia', 'retiro'),
    ('05615', 'Rionegro', 'Antioquia', 'rionegro-antioquia'),
    ('05628', 'Sabanalarga', 'Antioquia', 'sabanalarga-antioquia'),
    ('05631', 'Sabaneta', 'Antioquia', 'sabaneta'),
    ('05642', 'Salgar', 'Antioquia', 'salgar'),
    ('05647', 'San Andrés de Cuerquía', 'Antioquia', 'san-andres-de-cuerquia'),
    ('05649', 'San Carlos', 'Antioquia', 'san-carlos-antioquia'),
    ('05652', 'San Francisco', 'Antioquia', 'san-francisco-antioquia'),
    ('05656', 'San Jerónimo', 'Antioquia', 'san-jeronimo'),
    ('05658', 'San José de la Montaña', 'Antioquia', 'san-jose-de-la-montana'),
    ('05659', 'San Juan de Urabá', 'Antioquia', 'san-juan-de-uraba'),
    ('05660', 'San Luis', 'Antioquia', 'san-luis-antioquia'),
    ('05664', 'San Pedro de los Milagros', 'Antioquia', 'san-pedro-de-los-milagros'),
    ('05665', 'San Pedro de Urabá', 'Antioquia', 'san-pedro-de-uraba'),
    ('05667', 'San Rafael', 'Antioquia', 'san-rafael'),
    ('05670', 'San Roque', 'Antioquia', 'san-roque'),
    ('05674', 'San Vicente Ferrer', 'Antioquia', 'san-vicente-ferrer'),
    ('05679', 'Santa Bárbara', 'Antioquia', 'santa-barbara-antioquia'),
    ('05686', 'Santa Rosa de Osos', 'Antioquia', 'santa-rosa-de-osos'),
    ('05690', 'Santo Domingo', 'Antioquia', 'santo-domingo'),
    ('05697', 'El Santuario', 'Antioquia', 'el-santuario'),
    ('05736', 'Segovia', 'Antioquia', 'segovia'),
    ('05756', 'Sonsón', 'Antioquia', 'sonson'),
    ('05761', 'Sopetrán', 'Antioquia', 'sopetran'),
    ('05789', 'Támesis', 'Antioquia', 'tamesis'),
    ('05790', 'Tarazá', 'Antioquia', 'taraza'),
    ('05792', 'Tarso', 'Antioquia', 'tarso'),
    ('05809', 'Titiribí', 'Antioquia', 'titiribi'),
    ('05819', 'Toledo', 'Antioquia', 'toledo-antioquia'),
    ('05837', 'Turbo', 'Antioquia', 'turbo'),
    ('05842', 'Uramita', 'Antioquia', 'uramita'),
    ('05847', 'Urrao', 'Antioquia', 'urrao'),
    ('05854', 'Valdivia', 'Antioquia', 'valdivia'),
    ('05856', 'Valparaíso', 'Antioquia', 'valparaiso-antioquia'),
    ('05858', 'Vegachí', 'Antioquia', 'vegachi'),
    ('05861', 'Venecia', 'Antioquia', 'venecia-antioquia'),
    ('05873', 'Vigía del Fuerte', 'Antioquia', 'vigia-del-fuerte'),
    ('05885', 'Yalí', 'Antioquia', 'yali'),
    ('05887', 'Yarumal', 'Antioquia', 'yarumal'),
    ('05890', 'Yolombó', 'Antioquia', 'yolombo'),
    ('05893', 'Yondó', 'Antioquia', 'yondo'),
    ('05895', 'Zaragoza', 'Antioquia', 'zaragoza'),
    ('08001', 'Barranquilla', 'Atlántico', 'barranquilla'),
    ('08078', 'Baranoa', 'Atlántico', 'baranoa'),
    ('08137', 'Campo de la Cruz', 'Atlántico', 'campo-de-la-cruz'),
    ('08141', 'Candelaria', 'Atlántico', 'candelaria-atlantico'),
    ('08296', 'Galapa', 'Atlántico', 'galapa'),
    ('08372', 'Juan de Acosta', 'Atlántico', 'juan-de-acosta'),
    ('08421', 'Luruaco', 'Atlántico', 'luruaco'),
    ('08433', 'Malambo', 'Atlántico', 'malambo'),
    ('08436', 'Manatí', 'Atlántico', 'manati'),
    ('08520', 'Palmar de Varela', 'Atlántico', 'palmar-de-varela'),
    ('08549', 'Piojó', 'Atlántico', 'piojo'),
    ('08558', 'Polonuevo', 'Atlántico', 'polonuevo'),
    ('08560', 'Ponedera', 'Atlántico', 'ponedera'),
    ('08573', 'Puerto Colombia', 'Atlántico', 'puerto-colombia-atlantico'),
    ('08606', 'Repelón', 'Atlántico', 'repelon'),
    ('08634', 'Sabanagrande', 'Atlántico', 'sabanagrande'),
    ('08638', 'Sabanalarga', 'Atlántico', 'sabanalarga-atlantico'),
    ('08675', 'Santa Lucía', 'Atlántico', 'santa-lucia'),
    ('08685', 'Santo Tomás', 'Atlántico', 'santo-tomas'),
    ('08758', 'Soledad', 'Atlántico', 'soledad'),
    ('08770', 'Suan', 'Atlántico', 'suan'),
    ('08832', 'Tubará', 'Atlántico', 'tubara'),
    ('08849', 'Usiacurí', 'Atlántico', 'usiacuri'),
    ('11001', 'Bogotá', 'Bogotá, D.C.', 'bogota'),
    ('13001', 'Cartagena de Indias', 'Bolívar', 'cartagena-de-indias'),
    ('13006', 'Achí', 'Bolívar', 'achi'),
    ('13030', 'Altos del Rosario', 'Bolívar', 'altos-del-rosario'),
    ('13042', 'Arenal', 'Bolívar', 'arenal'),
    ('13052', 'Arjona', 'Bolívar', 'arjona'),
    ('13062', 'Arroyohondo', 'Bolívar', 'arroyohondo'),
    ('13074', 'Barranco de Loba', 'Bolívar', 'barranco-de-loba'),
    ('13140', 'Calamar', 'Bolívar', 'calamar-bolivar'),
    ('13160', 'Cantagallo', 'Bolívar', 'cantagallo'),
    ('13188', 'Cicuco', 'Bolívar', 'cicuco'),
    ('13212', 'Córdoba', 'Bolívar', 'cordoba-bolivar'),
    ('13222', 'Clemencia', 'Bolívar', 'clemencia'),
    ('13244', 'El Carmen de Bolívar', 'Bolívar', 'el-carmen-de-bolivar'),
    ('13248', 'El Guamo', 'Bolívar', 'el-guamo'),
    ('13268', 'El Peñón', 'Bolívar', 'el-penon-bolivar'),
    ('13300', 'Hatillo de Loba', 'Bolívar', 'hatillo-de-loba'),
    ('13430', 'Magangué', 'Bolívar', 'magangue'),
    ('13433', 'Mahates', 'Bolívar', 'mahates'),
    ('13440', 'Margarita', 'Bolívar', 'margarita'),
    ('13442', 'María la Baja', 'Bolívar', 'maria-la-baja'),
    ('13458', 'Montecristo', 'Bolívar', 'montecristo'),
    ('13468', 'Santa Cruz de Mompox', 'Bolívar', 'santa-cruz-de-mompox'),
    ('13473', 'Morales', 'Bolívar', 'morales-bolivar'),
    ('13490', 'Norosí', 'Bolívar', 'norosi'),
    ('13549', 'Pinillos', 'Bolívar', 'pinillos'),
    ('13580', 'Regidor', 'Bolívar', 'regidor'),
    ('13600', 'Río Viejo', 'Bolívar', 'rio-viejo'),
    ('13620', 'San Cristóbal', 'Bolívar', 'san-cristobal'),
    ('13647', 'San Estanislao', 'Bolívar', 'san-estanislao'),
    ('13650', 'San Fernando', 'Bolívar', 'san-fernando'),
    ('13654', 'San Jacinto', 'Bolívar', 'san-jacinto'),
    ('13655', 'San Jacinto del Cauca', 'Bolívar', 'san-jacinto-del-cauca'),
    ('13657', 'San Juan Nepomuceno', 'Bolívar', 'san-juan-nepomuceno'),
    ('13667', 'San Martín de Loba', 'Bolívar', 'san-martin-de-loba'),
    ('13670', 'San Pablo', 'Bolívar', 'san-pablo-bolivar'),
    ('13673', 'Santa Catalina', 'Bolívar', 'santa-catalina'),
    ('13683', 'Santa Rosa', 'Bolívar', 'santa-rosa-bolivar'),
    ('13688', 'Santa Rosa del Sur', 'Bolívar', 'santa-rosa-del-sur'),
    ('13744', 'Simití', 'Bolívar', 'simiti'),
    ('13760', 'Soplaviento', 'Bolívar', 'soplaviento'),
    ('13780', 'Talaigua Nuevo', 'Bolívar', 'talaigua-nuevo'),
    ('13810', 'Tiquisio', 'Bolívar', 'tiquisio'),
    ('13836', 'Turbaco', 'Bolívar', 'turbaco'),
    ('13838', 'Turbaná', 'Bolívar', 'turbana'),
    ('13873', 'Villanueva', 'Bolívar', 'villanueva-bolivar'),
    ('13894', 'Zambrano', 'Bolívar', 'zambrano'),
    ('15001', 'Tunja', 'Boyacá', 'tunja'),
    ('15022', 'Almeida', 'Boyacá', 'almeida'),
    ('15047', 'Aquitania', 'Boyacá', 'aquitania'),
    ('15051', 'Arcabuco', 'Boyacá', 'arcabuco'),
    ('15087', 'Belén', 'Boyacá', 'belen-boyaca'),
    ('15090', 'Berbeo', 'Boyacá', 'berbeo'),
    ('15092', 'Betéitiva', 'Boyacá', 'beteitiva'),
    ('15097', 'Boavita', 'Boyacá', 'boavita'),
    ('15104', 'Boyacá', 'Boyacá', 'boyaca'),
    ('15106', 'Briceño', 'Boyacá', 'briceno-boyaca'),
    ('15109', 'Buenavista', 'Boyacá', 'buenavista-boyaca'),
    ('15114', 'Busbanzá', 'Boyacá', 'busbanza'),
    ('15131', 'Caldas', 'Boyacá', 'caldas-boyaca'),
    ('15135', 'Campohermoso', 'Boyacá', 'campohermoso'),
    ('15162', 'Cerinza', 'Boyacá', 'cerinza'),
    ('15172', 'Chinavita', 'Boyacá', 'chinavita'),
    ('15176', 'Chiquinquirá', 'Boyacá', 'chiquinquira'),
    ('15180', 'Chiscas', 'Boyacá', 'chiscas'),
    ('15183', 'Chita', 'Boyacá', 'chita'),
    ('15185', 'Chitaraque', 'Boyacá', 'chitaraque'),
    ('15187', 'Chivatá', 'Boyacá', 'chivata'),
    ('15189', 'Ciénega', 'Boyacá', 'cienega'),
    ('15204', 'Cómbita', 'Boyacá', 'combita'),
    ('15212', 'Coper', 'Boyacá', 'coper'),
    ('15215', 'Corrales', 'Boyacá', 'corrales'),
    ('15218', 'Covarachía', 'Boyacá', 'covarachia'),
    ('15223', 'Cubará', 'Boyacá', 'cubara'),
    ('15224', 'Cucaita', 'Boyacá', 'cucaita'),
    ('15226', 'Cuítiva', 'Boyacá', 'cuitiva'),
    ('15232', 'Chíquiza', 'Boyacá', 'chiquiza'),
    ('15236', 'Chivor', 'Boyacá', 'chivor'),
    ('15238', 'Duitama', 'Boyacá', 'duitama'),
    ('15244', 'El Cocuy', 'Boyacá', 'el-cocuy'),
    ('15248', 'El Espino', 'Boyacá', 'el-espino'),
    ('15272', 'Firavitoba', 'Boyacá', 'firavitoba'),
    ('15276', 'Floresta', 'Boyacá', 'floresta'),
    ('15293', 'Gachantivá', 'Boyacá', 'gachantiva'),
    ('15296', 'Gámeza', 'Boyacá', 'gameza'),
    ('15299', 'Garagoa', 'Boyacá', 'garagoa'),
    ('15317', 'Guacamayas', 'Boyacá', 'guacamayas'),
    ('15322', 'Guateque', 'Boyacá', 'guateque'),
    ('15325', 'Guayatá', 'Boyacá', 'guayata'),
    ('15332', 'Güicán de la Sierra', 'Boyacá', 'guican-de-la-sierra'),
    ('15362', 'Iza', 'Boyacá', 'iza'),
    ('15367', 'Jenesano', 'Boyacá', 'jenesano'),
    ('15368', 'Jericó', 'Boyacá', 'jerico-boyaca'),
    ('15377', 'Labranzagrande', 'Boyacá', 'labranzagrande'),
    ('15380', 'La Capilla', 'Boyacá', 'la-capilla'),
    ('15401', 'La Victoria', 'Boyacá', 'la-victoria-boyaca'),
    ('15403', 'La Uvita', 'Boyacá', 'la-uvita'),
    ('15407', 'Villa de Leyva', 'Boyacá', 'villa-de-leyva'),
    ('15425', 'Macanal', 'Boyacá', 'macanal'),
    ('15442', 'Maripí', 'Boyacá', 'maripi'),
    ('15455', 'Miraflores', 'Boyacá', 'miraflores-boyaca'),
    ('15464', 'Mongua', 'Boyacá', 'mongua'),
    ('15466', 'Monguí', 'Boyacá', 'mongui'),
    ('15469', 'Moniquirá', 'Boyacá', 'moniquira'),
    ('15476', 'Motavita', 'Boyacá', 'motavita'),
    ('15480', 'Muzo', 'Boyacá', 'muzo'),
    ('15491', 'Nobsa', 'Boyacá', 'nobsa'),
    ('15494', 'Nuevo Colón', 'Boyacá', 'nuevo-colon'),
    ('15500', 'Oicatá', 'Boyacá', 'oicata'),
    ('15507', 'Otanche', 'Boyacá', 'otanche'),
    ('15511', 'Pachavita', 'Boyacá', 'pachavita'),
    ('15514', 'Páez', 'Boyacá', 'paez-boyaca'),
    ('15516', 'Paipa', 'Boyacá', 'paipa'),
    ('15518', 'Pajarito', 'Boyacá', 'pajarito'),
    ('15522', 'Panqueba', 'Boyacá', 'panqueba'),
    ('15531', 'Pauna', 'Boyacá', 'pauna'),
    ('15533', 'Paya', 'Boyacá', 'paya'),
    ('15537', 'Paz de Río', 'Boyacá', 'paz-de-rio'),
    ('15542', 'Pesca', 'Boyacá', 'pesca'),
    ('15550', 'Pisba', 'Boyacá', 'pisba'),
    ('15572', 'Puerto Boyacá', 'Boyacá', 'puerto-boyaca'),
    ('15580', 'Quípama', 'Boyacá', 'quipama'),
    ('15599', 'Ramiriquí', 'Boyacá', 'ramiriqui'),
    ('15600', 'Ráquira', 'Boyacá', 'raquira'),
    ('15621', 'Rondón', 'Boyacá', 'rondon'),
    ('15632', 'Saboyá', 'Boyacá', 'saboya'),
    ('15638', 'Sáchica', 'Boyacá', 'sachica'),
    ('15646', 'Samacá', 'Boyacá', 'samaca'),
    ('15660', 'San Eduardo', 'Boyacá', 'san-eduardo'),
    ('15664', 'San José de Pare', 'Boyacá', 'san-jose-de-pare'),
    ('15667', 'San Luis de Gaceno', 'Boyacá', 'san-luis-de-gaceno'),
    ('15673', 'San Mateo', 'Boyacá', 'san-mateo'),
    ('15676', 'San Miguel de Sema', 'Boyacá', 'san-miguel-de-sema'),
    ('15681', 'San Pablo de Borbur', 'Boyacá', 'san-pablo-de-borbur'),
    ('15686', 'Santana', 'Boyacá', 'santana'),
    ('15690', 'Santa María', 'Boyacá', 'santa-maria-boyaca'),
    ('15693', 'Santa Rosa de Viterbo', 'Boyacá', 'santa-rosa-de-viterbo'),
    ('15696', 'Santa Sofía', 'Boyacá', 'santa-sofia'),
    ('15720', 'Sativanorte', 'Boyacá', 'sativanorte'),
    ('15723', 'Sativasur', 'Boyacá', 'sativasur'),
    ('15740', 'Siachoque', 'Boyacá', 'siachoque'),
    ('15753', 'Soatá', 'Boyacá', 'soata'),
    ('15755', 'Socotá', 'Boyacá', 'socota'),
    ('15757', 'Socha', 'Boyacá', 'socha'),
    ('15759', 'Sogamoso', 'Boyacá', 'sogamoso'),
    ('15761', 'Somondoco', 'Boyacá', 'somondoco'),
    ('15762', 'Sora', 'Boyacá', 'sora'),
    ('15763', 'Sotaquirá', 'Boyacá', 'sotaquira'),
    ('15764', 'Soracá', 'Boyacá', 'soraca'),
    ('15774', 'Susacón', 'Boyacá', 'susacon'),
    ('15776', 'Sutamarchán', 'Boyacá', 'sutamarchan'),
    ('15778', 'Sutatenza', 'Boyacá', 'sutatenza'),
    ('15790', 'Tasco', 'Boyacá', 'tasco'),
    ('15798', 'Tenza', 'Boyacá', 'tenza'),
    ('15804', 'Tibaná', 'Boyacá', 'tibana'),
    ('15806', 'Tibasosa', 'Boyacá', 'tibasosa'),
    ('15808', 'Tinjacá', 'Boyacá', 'tinjaca'),
    ('15810', 'Tipacoque', 'Boyacá', 'tipacoque'),
    ('15814', 'Toca', 'Boyacá', 'toca'),
    ('15816', 'Togüí', 'Boyacá', 'togui'),
    ('15820', 'Tópaga', 'Boyacá', 'topaga'),
    ('15822', 'Tota', 'Boyacá', 'tota'),
    ('15832', 'Tununguá', 'Boyacá', 'tunungua'),
    ('15835', 'Turmequé', 'Boyacá', 'turmeque'),
    ('15837', 'Tuta', 'Boyacá', 'tuta'),
    ('15839', 'Tutazá', 'Boyacá', 'tutaza'),
    ('15842', 'Úmbita', 'Boyacá', 'umbita'),
    ('15861', 'Ventaquemada', 'Boyacá', 'ventaquemada'),
    ('15879', 'Viracachá', 'Boyacá', 'viracacha'),
    ('15897', 'Zetaquira', 'Boyacá', 'zetaquira'),
    ('17001', 'Manizales', 'Caldas', 'manizales'),
    ('17013', 'Aguadas', 'Caldas', 'aguadas'),
    ('17042', 'Anserma', 'Caldas', 'anserma'),
    ('17050', 'Aranzazu', 'Caldas', 'aranzazu'),
    ('17088', 'Belalcázar', 'Caldas', 'belalcazar'),
    ('17174', 'Chinchiná', 'Caldas', 'chinchina'),
    ('17272', 'Filadelfia', 'Caldas', 'filadelfia'),
    ('17380', 'La Dorada', 'Caldas', 'la-dorada'),
    ('17388', 'La Merced', 'Caldas', 'la-merced'),
    ('17433', 'Manzanares', 'Caldas', 'manzanares'),
    ('17442', 'Marmato', 'Caldas', 'marmato'),
    ('17444', 'Marquetalia', 'Caldas', 'marquetalia'),
    ('17446', 'Marulanda', 'Caldas', 'marulanda'),
    ('17486', 'Neira', 'Caldas', 'neira'),
    ('17495', 'Norcasia', 'Caldas', 'norcasia'),
    ('17513', 'Pácora', 'Caldas', 'pacora'),
    ('17524', 'Palestina', 'Caldas', 'palestina-caldas'),
    ('17541', 'Pensilvania', 'Caldas', 'pensilvania'),
    ('17614', 'Riosucio', 'Caldas', 'riosucio-caldas'),
    ('17616', 'Risaralda', 'Caldas', 'risaralda'),
    ('17653', 'Salamina', 'Caldas', 'salamina-caldas'),
    ('17662', 'Samaná', 'Caldas', 'samana'),
    ('17665', 'San José', 'Caldas', 'san-jose'),
    ('17777', 'Supía', 'Caldas', 'supia'),
    ('17867', 'Victoria', 'Caldas', 'victoria'),
    ('17873', 'Villamaría', 'Caldas', 'villamaria'),
    ('17877', 'Viterbo', 'Caldas', 'viterbo'),
    ('18001', 'Florencia', 'Caquetá', 'florencia-caqueta'),
    ('18029', 'Albania', 'Caquetá', 'albania-caqueta'),
    ('18094', 'Belén de los Andaquíes', 'Caquetá', 'belen-de-los-andaquies'),
    ('18150', 'Cartagena del Chairá', 'Caquetá', 'cartagena-del-chaira'),
    ('18205', 'Curillo', 'Caquetá', 'curillo'),
    ('18247', 'El Doncello', 'Caquetá', 'el-doncello'),
    ('18256', 'El Paujíl', 'Caquetá', 'el-paujil'),
    ('18410', 'La Montañita', 'Caquetá', 'la-montanita'),
    ('18460', 'Milán', 'Caquetá', 'milan'),
    ('18479', 'Morelia', 'Caquetá', 'morelia'),
    ('18592', 'Puerto Rico', 'Caquetá', 'puerto-rico-caqueta'),
    ('18610', 'San José del Fragua', 'Caquetá', 'san-jose-del-fragua'),
    ('18753', 'San Vicente del Caguán', 'Caquetá', 'san-vicente-del-caguan'),
    ('18756', 'Solano', 'Caquetá', 'solano'),
    ('18785', 'Solita', 'Caquetá', 'solita'),
    ('18860', 'Valparaíso', 'Caquetá', 'valparaiso-caqueta'),
    ('19001', 'Popayán', 'Cauca', 'popayan'),
    ('19022', 'Almaguer', 'Cauca', 'almaguer'),
    ('19050', 'Argelia', 'Cauca', 'argelia-cauca'),
    ('19075', 'Balboa', 'Cauca', 'balboa-cauca'),
    ('19100', 'Bolívar', 'Cauca', 'bolivar-cauca'),
    ('19110', 'Buenos Aires', 'Cauca', 'buenos-aires'),
    ('19130', 'Cajibío', 'Cauca', 'cajibio'),
    ('19137', 'Caldono', 'Cauca', 'caldono'),
    ('19142', 'Caloto', 'Cauca', 'caloto'),
    ('19212', 'Corinto', 'Cauca', 'corinto'),
    ('19256', 'El Tambo', 'Cauca', 'el-tambo-cauca'),
    ('19290', 'Florencia', 'Cauca', 'florencia-cauca'),
    ('19300', 'Guachené', 'Cauca', 'guachene'),
    ('19318', 'Guapi', 'Cauca', 'guapi'),
    ('19355', 'Inzá', 'Cauca', 'inza'),
    ('19364', 'Jambaló', 'Cauca', 'jambalo'),
    ('19392', 'La Sierra', 'Cauca', 'la-sierra'),
    ('19397', 'La Vega', 'Cauca', 'la-vega-cauca'),
    ('19418', 'López de Micay', 'Cauca', 'lopez-de-micay'),
    ('19450', 'Mercaderes', 'Cauca', 'mercaderes'),
    ('19455', 'Miranda', 'Cauca', 'miranda'),
    ('19473', 'Morales', 'Cauca', 'morales-cauca'),
    ('19513', 'Padilla', 'Cauca', 'padilla'),
    ('19517', 'Páez', 'Cauca', 'paez-cauca'),
    ('19532', 'Patía', 'Cauca', 'patia'),
    ('19533', 'Piamonte', 'Cauca', 'piamonte'),
    ('19548', 'Piendamó - Tunía', 'Cauca', 'piendamo-tunia'),
    ('19573', 'Puerto Tejada', 'Cauca', 'puerto-tejada'),
    ('19585', 'Puracé', 'Cauca', 'purace'),
    ('19622', 'Rosas', 'Cauca', 'rosas'),
    ('19693', 'San Sebastián', 'Cauca', 'san-sebastian'),
    ('19698', 'Santander de Quilichao', 'Cauca', 'santander-de-quilichao'),
    ('19701', 'Santa Rosa', 'Cauca', 'santa-rosa-cauca'),
    ('19743', 'Silvia', 'Cauca', 'silvia'),
    ('19760', 'Sotará - Paispamba', 'Cauca', 'sotara-paispamba'),
    ('19780', 'Suárez', 'Cauca', 'suarez-cauca'),
    ('19785', 'Sucre', 'Cauca', 'sucre-cauca'),
    ('19807', 'Timbío', 'Cauca', 'timbio'),
    ('19809', 'Timbiquí', 'Cauca', 'timbiqui'),
    ('19821', 'Toribío', 'Cauca', 'toribio'),
    ('19824', 'Totoró', 'Cauca', 'totoro'),
    ('19845', 'Villa Rica', 'Cauca', 'villa-rica'),
    ('20001', 'Valledupar', 'Cesar', 'valledupar'),
    ('20011', 'Aguachica', 'Cesar', 'aguachica'),
    ('20013', 'Agustín Codazzi', 'Cesar', 'agustin-codazzi'),
    ('20032', 'Astrea', 'Cesar', 'astrea'),
    ('20045', 'Becerril', 'Cesar', 'becerril'),
    ('20060', 'Bosconia', 'Cesar', 'bosconia'),
    ('20175', 'Chimichagua', 'Cesar', 'chimichagua'),
    ('20178', 'Chiriguaná', 'Cesar', 'chiriguana'),
    ('20228', 'Curumaní', 'Cesar', 'curumani'),
    ('20238', 'El Copey', 'Cesar', 'el-copey'),
    ('20250', 'El Paso', 'Cesar', 'el-paso'),
    ('20295', 'Gamarra', 'Cesar', 'gamarra'),
    ('20310', 'González', 'Cesar', 'gonzalez'),
    ('20383', 'La Gloria', 'Cesar', 'la-gloria'),
    ('20400', 'La Jagua de Ibirico', 'Cesar', 'la-jagua-de-ibirico'),
    ('20443', 'Manaure Balcón del Cesar', 'Cesar', 'manaure-balcon-del-cesar'),
    ('20517', 'Pailitas', 'Cesar', 'pailitas'),
    ('20550', 'Pelaya', 'Cesar', 'pelaya'),
    ('20570', 'Pueblo Bello', 'Cesar', 'pueblo-bello'),
    ('20614', 'Río de Oro', 'Cesar', 'rio-de-oro'),
    ('20621', 'La Paz', 'Cesar', 'la-paz-cesar'),
    ('20710', 'San Alberto', 'Cesar', 'san-alberto'),
    ('20750', 'San Diego', 'Cesar', 'san-diego'),
    ('20770', 'San Martín', 'Cesar', 'san-martin-cesar'),
    ('20787', 'Tamalameque', 'Cesar', 'tamalameque'),
    ('23001', 'Montería', 'Córdoba', 'monteria'),
    ('23068', 'Ayapel', 'Córdoba', 'ayapel'),
    ('23079', 'Buenavista', 'Córdoba', 'buenavista-cordoba'),
    ('23090', 'Canalete', 'Córdoba', 'canalete'),
    ('23162', 'Cereté', 'Córdoba', 'cerete'),
    ('23168', 'Chimá', 'Córdoba', 'chima-cordoba'),
    ('23182', 'Chinú', 'Córdoba', 'chinu'),
    ('23189', 'Ciénaga de Oro', 'Córdoba', 'cienaga-de-oro'),
    ('23300', 'Cotorra', 'Córdoba', 'cotorra'),
    ('23350', 'La Apartada', 'Córdoba', 'la-apartada'),
    ('23417', 'Lorica', 'Córdoba', 'lorica'),
    ('23419', 'Los Córdobas', 'Córdoba', 'los-cordobas'),
    ('23464', 'Momil', 'Córdoba', 'momil'),
    ('23466', 'Montelíbano', 'Córdoba', 'montelibano'),
    ('23500', 'Moñitos', 'Córdoba', 'monitos'),
    ('23555', 'Planeta Rica', 'Córdoba', 'planeta-rica'),
    ('23570', 'Pueblo Nuevo', 'Córdoba', 'pueblo-nuevo'),
    ('23574', 'Puerto Escondido', 'Córdoba', 'puerto-escondido'),
    ('23580', 'Puerto Libertador', 'Córdoba', 'puerto-libertador'),
    ('23586', 'Purísima de la Concepción', 'Córdoba', 'purisima-de-la-concepcion'),
    ('23660', 'Sahagún', 'Córdoba', 'sahagun'),
    ('23670', 'San Andrés de Sotavento', 'Córdoba', 'san-andres-de-sotavento'),
    ('23672', 'San Antero', 'Córdoba', 'san-antero'),
    ('23675', 'San Bernardo del Viento', 'Córdoba', 'san-bernardo-del-viento'),
    ('23678', 'San Carlos', 'Córdoba', 'san-carlos-cordoba'),
    ('23682', 'San José de Uré', 'Córdoba', 'san-jose-de-ure'),
    ('23686', 'San Pelayo', 'Córdoba', 'san-pelayo'),
    ('23807', 'Tierralta', 'Córdoba', 'tierralta'),
    ('23815', 'Tuchín', 'Córdoba', 'tuchin'),
    ('23855', 'Valencia', 'Córdoba', 'valencia'),
    ('25001', 'Agua de Dios', 'Cundinamarca', 'agua-de-dios'),
    ('25019', 'Albán', 'Cundinamarca', 'alban-cundinamarca'),
    ('25035', 'Anapoima', 'Cundinamarca', 'anapoima'),
    ('25040', 'Anolaima', 'Cundinamarca', 'anolaima'),
    ('25053', 'Arbeláez', 'Cundinamarca', 'arbelaez'),
    ('25086', 'Beltrán', 'Cundinamarca', 'beltran'),
    ('25095', 'Bituima', 'Cundinamarca', 'bituima'),
    ('25099', 'Bojacá', 'Cundinamarca', 'bojaca'),
    ('25120', 'Cabrera', 'Cundinamarca', 'cabrera-cundinamarca'),
    ('25123', 'Cachipay', 'Cundinamarca', 'cachipay'),
    ('25126', 'Cajicá', 'Cundinamarca', 'cajica'),
    ('25148', 'Caparrapí', 'Cundinamarca', 'caparrapi'),
    ('25151', 'Cáqueza', 'Cundinamarca', 'caqueza'),
    ('25154', 'Carmen de Carupa', 'Cundinamarca', 'carmen-de-carupa'),
    ('25168', 'Chaguaní', 'Cundinamarca', 'chaguani'),
    ('25175', 'Chía', 'Cundinamarca', 'chia'),
    ('25178', 'Chipaque', 'Cundinamarca', 'chipaque'),
    ('25181', 'Choachí', 'Cundinamarca', 'choachi'),
    ('25183', 'Chocontá', 'Cundinamarca', 'choconta'),
    ('25200', 'Cogua', 'Cundinamarca', 'cogua'),
    ('25214', 'Cota', 'Cundinamarca', 'cota'),
    ('25224', 'Cucunubá', 'Cundinamarca', 'cucunuba'),
    ('25245', 'El Colegio', 'Cundinamarca', 'el-colegio'),
    ('25258', 'El Peñón', 'Cundinamarca', 'el-penon-cundinamarca'),
    ('25260', 'El Rosal', 'Cundinamarca', 'el-rosal'),
    ('25269', 'Facatativá', 'Cundinamarca', 'facatativa'),
    ('25279', 'Fómeque', 'Cundinamarca', 'fomeque'),
    ('25281', 'Fosca', 'Cundinamarca', 'fosca'),
    ('25286', 'Funza', 'Cundinamarca', 'funza'),
    ('25288', 'Fúquene', 'Cundinamarca', 'fuquene'),
    ('25290', 'Fusagasugá', 'Cundinamarca', 'fusagasuga'),
    ('25293', 'Gachalá', 'Cundinamarca', 'gachala'),
    ('25295', 'Gachancipá', 'Cundinamarca', 'gachancipa'),
    ('25297', 'Gachetá', 'Cundinamarca', 'gacheta'),
    ('25299', 'Gama', 'Cundinamarca', 'gama'),
    ('25307', 'Girardot', 'Cundinamarca', 'girardot'),
    ('25312', 'Granada', 'Cundinamarca', 'granada-cundinamarca'),
    ('25317', 'Guachetá', 'Cundinamarca', 'guacheta'),
    ('25320', 'Guaduas', 'Cundinamarca', 'guaduas'),
    ('25322', 'Guasca', 'Cundinamarca', 'guasca'),
    ('25324', 'Guataquí', 'Cundinamarca', 'guataqui'),
    ('25326', 'Guatavita', 'Cundinamarca', 'guatavita'),
    ('25328', 'Guayabal de Síquima', 'Cundinamarca', 'guayabal-de-siquima'),
    ('25335', 'Guayabetal', 'Cundinamarca', 'guayabetal'),
    ('25339', 'Gutiérrez', 'Cundinamarca', 'gutierrez'),
    ('25368', 'Jerusalén', 'Cundinamarca', 'jerusalen'),
    ('25372', 'Junín', 'Cundinamarca', 'junin'),
    ('25377', 'La Calera', 'Cundinamarca', 'la-calera'),
    ('25386', 'La Mesa', 'Cundinamarca', 'la-mesa'),
    ('25394', 'La Palma', 'Cundinamarca', 'la-palma'),
    ('25398', 'La Peña', 'Cundinamarca', 'la-pena'),
    ('25402', 'La Vega', 'Cundinamarca', 'la-vega-cundinamarca'),
    ('25407', 'Lenguazaque', 'Cundinamarca', 'lenguazaque'),
    ('25426', 'Machetá', 'Cundinamarca', 'macheta'),
    ('25430', 'Madrid', 'Cundinamarca', 'madrid'),
    ('25436', 'Manta', 'Cundinamarca', 'manta'),
    ('25438', 'Medina', 'Cundinamarca', 'medina'),
    ('25473', 'Mosquera', 'Cundinamarca', 'mosquera-cundinamarca'),
    ('25483', 'Nariño', 'Cundinamarca', 'narino-cundinamarca'),
    ('25486', 'Nemocón', 'Cundinamarca', 'nemocon'),
    ('25488', 'Nilo', 'Cundinamarca', 'nilo'),
    ('25489', 'Nimaima', 'Cundinamarca', 'nimaima'),
    ('25491', 'Nocaima', 'Cundinamarca', 'nocaima'),
    ('25506', 'Venecia', 'Cundinamarca', 'venecia-cundinamarca'),
    ('25513', 'Pacho', 'Cundinamarca', 'pacho'),
    ('25518', 'Paime', 'Cundinamarca', 'paime'),
    ('25524', 'Pandi', 'Cundinamarca', 'pandi'),
    ('25530', 'Paratebueno', 'Cundinamarca', 'paratebueno'),
    ('25535', 'Pasca', 'Cundinamarca', 'pasca'),
    ('25572', 'Puerto Salgar', 'Cundinamarca', 'puerto-salgar'),
    ('25580', 'Pulí', 'Cundinamarca', 'puli'),
    ('25592', 'Quebradanegra', 'Cundinamarca', 'quebradanegra'),
    ('25594', 'Quetame', 'Cundinamarca', 'quetame'),
    ('25596', 'Quipile', 'Cundinamarca', 'quipile'),
    ('25599', 'Apulo', 'Cundinamarca', 'apulo'),
    ('25612', 'Ricaurte', 'Cundinamarca', 'ricaurte-cundinamarca'),
    ('25645', 'San Antonio del Tequendama', 'Cundinamarca', 'san-antonio-del-tequendama'),
    ('25649', 'San Bernardo', 'Cundinamarca', 'san-bernardo-cundinamarca'),
    ('25653', 'San Cayetano', 'Cundinamarca', 'san-cayetano-cundinamarca'),
    ('25658', 'San Francisco', 'Cundinamarca', 'san-francisco-cundinamarca'),
    ('25662', 'San Juan de Rioseco', 'Cundinamarca', 'san-juan-de-rioseco'),
    ('25718', 'Sasaima', 'Cundinamarca', 'sasaima'),
    ('25736', 'Sesquilé', 'Cundinamarca', 'sesquile'),
    ('25740', 'Sibaté', 'Cundinamarca', 'sibate'),
    ('25743', 'Silvania', 'Cundinamarca', 'silvania'),
    ('25745', 'Simijaca', 'Cundinamarca', 'simijaca'),
    ('25754', 'Soacha', 'Cundinamarca', 'soacha'),
    ('25758', 'Sopó', 'Cundinamarca', 'sopo'),
    ('25769', 'Subachoque', 'Cundinamarca', 'subachoque'),
    ('25772', 'Suesca', 'Cundinamarca', 'suesca'),
    ('25777', 'Supatá', 'Cundinamarca', 'supata'),
    ('25779', 'Susa', 'Cundinamarca', 'susa'),
    ('25781', 'Sutatausa', 'Cundinamarca', 'sutatausa'),
    ('25785', 'Tabio', 'Cundinamarca', 'tabio'),
    ('25793', 'Tausa', 'Cundinamarca', 'tausa'),
    ('25797', 'Tena', 'Cundinamarca', 'tena'),
    ('25799', 'Tenjo', 'Cundinamarca', 'tenjo'),
    ('25805', 'Tibacuy', 'Cundinamarca', 'tibacuy'),
    ('25807', 'Tibirita', 'Cundinamarca', 'tibirita'),
    ('25815', 'Tocaima', 'Cundinamarca', 'tocaima'),
    ('25817', 'Tocancipá', 'Cundinamarca', 'tocancipa'),
    ('25823', 'Topaipí', 'Cundinamarca', 'topaipi'),
    ('25839', 'Ubalá', 'Cundinamarca', 'ubala'),
    ('25841', 'Ubaque', 'Cundinamarca', 'ubaque'),
    ('25843', 'Villa de San Diego de Ubaté', 'Cundinamarca', 'villa-de-san-diego-de-ubate'),
    ('25845', 'Une', 'Cundinamarca', 'une'),
    ('25851', 'Útica', 'Cundinamarca', 'utica'),
    ('25862', 'Vergara', 'Cundinamarca', 'vergara'),
    ('25867', 'Vianí', 'Cundinamarca', 'viani'),
    ('25871', 'Villagómez', 'Cundinamarca', 'villagomez'),
    ('25873', 'Villapinzón', 'Cundinamarca', 'villapinzon'),
    ('25875', 'Villeta', 'Cundinamarca', 'villeta'),
    ('25878', 'Viotá', 'Cundinamarca', 'viota'),
    ('25885', 'Yacopí', 'Cundinamarca', 'yacopi'),
    ('25898', 'Zipacón', 'Cundinamarca', 'zipacon'),
    ('25899', 'Zipaquirá', 'Cundinamarca', 'zipaquira'),
    ('27001', 'Quibdó', 'Chocó', 'quibdo'),
    ('27006', 'Acandí', 'Chocó', 'acandi'),
    ('27025', 'Alto Baudó', 'Chocó', 'alto-baudo'),
    ('27050', 'Atrato', 'Chocó', 'atrato'),
    ('27073', 'Bagadó', 'Chocó', 'bagado'),
    ('27075', 'Bahía Solano', 'Chocó', 'bahia-solano'),
    ('27077', 'Bajo Baudó', 'Chocó', 'bajo-baudo'),
    ('27099', 'Bojayá', 'Chocó', 'bojaya'),
    ('27135', 'El Cantón del San Pablo', 'Chocó', 'el-canton-del-san-pablo'),
    ('27150', 'Carmen del Darién', 'Chocó', 'carmen-del-darien'),
    ('27160', 'Cértegui', 'Chocó', 'certegui'),
    ('27205', 'Condoto', 'Chocó', 'condoto'),
    ('27245', 'El Carmen de Atrato', 'Chocó', 'el-carmen-de-atrato'),
    ('27250', 'El Litoral del San Juan', 'Chocó', 'el-litoral-del-san-juan'),
    ('27361', 'Istmina', 'Chocó', 'istmina'),
    ('27372', 'Juradó', 'Chocó', 'jurado'),
    ('27413', 'Lloró', 'Chocó', 'lloro'),
    ('27425', 'Medio Atrato', 'Chocó', 'medio-atrato'),
    ('27430', 'Medio Baudó', 'Chocó', 'medio-baudo'),
    ('27450', 'Medio San Juan', 'Chocó', 'medio-san-juan'),
    ('27491', 'Nóvita', 'Chocó', 'novita'),
    ('27493', 'Nuevo Belén de Bajirá', 'Chocó', 'nuevo-belen-de-bajira'),
    ('27495', 'Nuquí', 'Chocó', 'nuqui'),
    ('27580', 'Río Iró', 'Chocó', 'rio-iro'),
    ('27600', 'Río Quito', 'Chocó', 'rio-quito'),
    ('27615', 'Riosucio', 'Chocó', 'riosucio-choco'),
    ('27660', 'San José del Palmar', 'Chocó', 'san-jose-del-palmar'),
    ('27745', 'Sipí', 'Chocó', 'sipi'),
    ('27787', 'Tadó', 'Chocó', 'tado'),
    ('27800', 'Unguía', 'Chocó', 'unguia'),
    ('27810', 'Unión Panamericana', 'Chocó', 'union-panamericana'),
    ('41001', 'Neiva', 'Huila', 'neiva'),
    ('41006', 'Acevedo', 'Huila', 'acevedo'),
    ('41013', 'Agrado', 'Huila', 'agrado'),
    ('41016', 'Aipe', 'Huila', 'aipe'),
    ('41020', 'Algeciras', 'Huila', 'algeciras'),
    ('41026', 'Altamira', 'Huila', 'altamira'),
    ('41078', 'Baraya', 'Huila', 'baraya'),
    ('41132', 'Campoalegre', 'Huila', 'campoalegre'),
    ('41206', 'Colombia', 'Huila', 'colombia'),
    ('41244', 'Elías', 'Huila', 'elias'),
    ('41298', 'Garzón', 'Huila', 'garzon'),
    ('41306', 'Gigante', 'Huila', 'gigante'),
    ('41319', 'Guadalupe', 'Huila', 'guadalupe-huila'),
    ('41349', 'Hobo', 'Huila', 'hobo'),
    ('41357', 'Íquira', 'Huila', 'iquira'),
    ('41359', 'Isnos', 'Huila', 'isnos'),
    ('41378', 'La Argentina', 'Huila', 'la-argentina'),
    ('41396', 'La Plata', 'Huila', 'la-plata'),
    ('41483', 'Nátaga', 'Huila', 'nataga'),
    ('41503', 'Oporapa', 'Huila', 'oporapa'),
    ('41518', 'Paicol', 'Huila', 'paicol'),
    ('41524', 'Palermo', 'Huila', 'palermo'),
    ('41530', 'Palestina', 'Huila', 'palestina-huila'),
    ('41548', 'Pital', 'Huila', 'pital'),
    ('41551', 'Pitalito', 'Huila', 'pitalito'),
    ('41615', 'Rivera', 'Huila', 'rivera'),
    ('41660', 'Saladoblanco', 'Huila', 'saladoblanco'),
    ('41668', 'San Agustín', 'Huila', 'san-agustin'),
    ('41676', 'Santa María', 'Huila', 'santa-maria-huila'),
    ('41770', 'Suaza', 'Huila', 'suaza'),
    ('41791', 'Tarqui', 'Huila', 'tarqui'),
    ('41797', 'Tesalia', 'Huila', 'tesalia'),
    ('41799', 'Tello', 'Huila', 'tello'),
    ('41801', 'Teruel', 'Huila', 'teruel'),
    ('41807', 'Timaná', 'Huila', 'timana'),
    ('41872', 'Villavieja', 'Huila', 'villavieja'),
    ('41885', 'Yaguará', 'Huila', 'yaguara'),
    ('44001', 'Riohacha', 'La Guajira', 'riohacha'),
    ('44035', 'Albania', 'La Guajira', 'albania-la-guajira'),
    ('44078', 'Barrancas', 'La Guajira', 'barrancas'),
    ('44090', 'Dibulla', 'La Guajira', 'dibulla'),
    ('44098', 'Distracción', 'La Guajira', 'distraccion'),
    ('44110', 'El Molino', 'La Guajira', 'el-molino'),
    ('44279', 'Fonseca', 'La Guajira', 'fonseca'),
    ('44378', 'Hatonuevo', 'La Guajira', 'hatonuevo'),
    ('44420', 'La Jagua del Pilar', 'La Guajira', 'la-jagua-del-pilar'),
    ('44430', 'Maicao', 'La Guajira', 'maicao'),
    ('44560', 'Manaure', 'La Guajira', 'manaure'),
    ('44650', 'San Juan del Cesar', 'La Guajira', 'san-juan-del-cesar'),
    ('44847', 'Uribia', 'La Guajira', 'uribia'),
    ('44855', 'Urumita', 'La Guajira', 'urumita'),
    ('44874', 'Villanueva', 'La Guajira', 'villanueva-la-guajira'),
    ('47001', 'Santa Marta', 'Magdalena', 'santa-marta'),
    ('47030', 'Algarrobo', 'Magdalena', 'algarrobo'),
    ('47053', 'Aracataca', 'Magdalena', 'aracataca'),
    ('47058', 'Ariguaní', 'Magdalena', 'ariguani'),
    ('47161', 'Cerro de San Antonio', 'Magdalena', 'cerro-de-san-antonio'),
    ('47170', 'Chivolo', 'Magdalena', 'chivolo'),
    ('47189', 'Ciénaga', 'Magdalena', 'cienaga'),
    ('47205', 'Concordia', 'Magdalena', 'concordia-magdalena'),
    ('47245', 'El Banco', 'Magdalena', 'el-banco'),
    ('47258', 'El Piñón', 'Magdalena', 'el-pinon'),
    ('47268', 'El Retén', 'Magdalena', 'el-reten'),
    ('47288', 'Fundación', 'Magdalena', 'fundacion'),
    ('47318', 'Guamal', 'Magdalena', 'guamal-magdalena'),
    ('47460', 'Nueva Granada', 'Magdalena', 'nueva-granada'),
    ('47541', 'Pedraza', 'Magdalena', 'pedraza'),
    ('47545', 'Pijiño del Carmen', 'Magdalena', 'pijino-del-carmen'),
    ('47551', 'Pivijay', 'Magdalena', 'pivijay'),
    ('47555', 'Plato', 'Magdalena', 'plato'),
    ('47570', 'Puebloviejo', 'Magdalena', 'puebloviejo'),
    ('47605', 'Remolino', 'Magdalena', 'remolino'),
    ('47660', 'Sabanas de San Ángel', 'Magdalena', 'sabanas-de-san-angel'),
    ('47675', 'Salamina', 'Magdalena', 'salamina-magdalena'),
    ('47692', 'San Sebastián de Buenavista', 'Magdalena', 'san-sebastian-de-buenavista'),
    ('47703', 'San Zenón', 'Magdalena', 'san-zenon'),
    ('47707', 'Santa Ana', 'Magdalena', 'santa-ana'),
    ('47720', 'Santa Bárbara de Pinto', 'Magdalena', 'santa-barbara-de-pinto'),
    ('47745', 'Sitionuevo', 'Magdalena', 'sitionuevo'),
    ('47798', 'Tenerife', 'Magdalena', 'tenerife'),
    ('47960', 'Zapayán', 'Magdalena', 'zapayan'),
    ('47980', 'Zona Bananera', 'Magdalena', 'zona-bananera'),
    ('50001', 'Villavicencio', 'Meta', 'villavicencio'),
    ('50006', 'Acacías', 'Meta', 'acacias'),
    ('50110', 'Barranca de Upía', 'Meta', 'barranca-de-upia'),
    ('50124', 'Cabuyaro', 'Meta', 'cabuyaro'),
    ('50150', 'Castilla la Nueva', 'Meta', 'castilla-la-nueva'),
    ('50223', 'Cubarral', 'Meta', 'cubarral'),
    ('50226', 'Cumaral', 'Meta', 'cumaral'),
    ('50245', 'El Calvario', 'Meta', 'el-calvario'),
    ('50251', 'El Castillo', 'Meta', 'el-castillo'),
    ('50270', 'El Dorado', 'Meta', 'el-dorado'),
    ('50287', 'Fuente de Oro', 'Meta', 'fuente-de-oro'),
    ('50313', 'Granada', 'Meta', 'granada-meta'),
    ('50318', 'Guamal', 'Meta', 'guamal-meta'),
    ('50325', 'Mapiripán', 'Meta', 'mapiripan'),
    ('50330', 'Mesetas', 'Meta', 'mesetas'),
    ('50350', 'La Macarena', 'Meta', 'la-macarena'),
    ('50370', 'Uribe', 'Meta', 'uribe'),
    ('50400', 'Lejanías', 'Meta', 'lejanias'),
    ('50450', 'Puerto Concordia', 'Meta', 'puerto-concordia'),
    ('50568', 'Puerto Gaitán', 'Meta', 'puerto-gaitan'),
    ('50573', 'Puerto López', 'Meta', 'puerto-lopez'),
    ('50577', 'Puerto Lleras', 'Meta', 'puerto-lleras'),
    ('50590', 'Puerto Rico', 'Meta', 'puerto-rico-meta'),
    ('50606', 'Restrepo', 'Meta', 'restrepo-meta'),
    ('50680', 'San Carlos de Guaroa', 'Meta', 'san-carlos-de-guaroa'),
    ('50683', 'San Juan de Arama', 'Meta', 'san-juan-de-arama'),
    ('50686', 'San Juanito', 'Meta', 'san-juanito'),
    ('50689', 'San Martín', 'Meta', 'san-martin-meta'),
    ('50711', 'Vistahermosa', 'Meta', 'vistahermosa'),
    ('52001', 'Pasto', 'Nariño', 'pasto'),
    ('52019', 'Albán', 'Nariño', 'alban-narino'),
    ('52022', 'Aldana', 'Nariño', 'aldana'),
    ('52036', 'Ancuya', 'Nariño', 'ancuya'),
    ('52051', 'Arboleda', 'Nariño', 'arboleda'),
    ('52079', 'Barbacoas', 'Nariño', 'barbacoas'),
    ('52083', 'Belén', 'Nariño', 'belen-narino'),
    ('52110', 'Buesaco', 'Nariño', 'buesaco'),
    ('52203', 'Colón', 'Nariño', 'colon-narino'),
    ('52207', 'Consacá', 'Nariño', 'consaca'),
    ('52210', 'Contadero', 'Nariño', 'contadero'),
    ('52215', 'Córdoba', 'Nariño', 'cordoba-narino'),
    ('52224', 'Cuaspud Carlosama', 'Nariño', 'cuaspud-carlosama'),
    ('52227', 'Cumbal', 'Nariño', 'cumbal'),
    ('52233', 'Cumbitara', 'Nariño', 'cumbitara'),
    ('52240', 'Chachagüí', 'Nariño', 'chachagui'),
    ('52250', 'El Charco', 'Nariño', 'el-charco'),
    ('52254', 'El Peñol', 'Nariño', 'el-penol'),
    ('52256', 'El Rosario', 'Nariño', 'el-rosario'),
    ('52258', 'El Tablón de Gómez', 'Nariño', 'el-tablon-de-gomez'),
    ('52260', 'El Tambo', 'Nariño', 'el-tambo-narino'),
    ('52287', 'Funes', 'Nariño', 'funes'),
    ('52317', 'Guachucal', 'Nariño', 'guachucal'),
    ('52320', 'Guaitarilla', 'Nariño', 'guaitarilla'),
    ('52323', 'Gualmatán', 'Nariño', 'gualmatan'),
    ('52352', 'Iles', 'Nariño', 'iles'),
    ('52354', 'Imués', 'Nariño', 'imues'),
    ('52356', 'Ipiales', 'Nariño', 'ipiales'),
    ('52378', 'La Cruz', 'Nariño', 'la-cruz'),
    ('52381', 'La Florida', 'Nariño', 'la-florida'),
    ('52385', 'La Llanada', 'Nariño', 'la-llanada'),
    ('52390', 'La Tola', 'Nariño', 'la-tola'),
    ('52399', 'La Unión', 'Nariño', 'la-union-narino'),
    ('52405', 'Leiva', 'Nariño', 'leiva'),
    ('52411', 'Linares', 'Nariño', 'linares'),
    ('52418', 'Los Andes', 'Nariño', 'los-andes'),
    ('52427', 'Magüí', 'Nariño', 'magui'),
    ('52435', 'Mallama', 'Nariño', 'mallama'),
    ('52473', 'Mosquera', 'Nariño', 'mosquera-narino'),
    ('52480', 'Nariño', 'Nariño', 'narino-narino'),
    ('52490', 'Olaya Herrera', 'Nariño', 'olaya-herrera'),
    ('52506', 'Ospina', 'Nariño', 'ospina'),
    ('52520', 'Francisco Pizarro', 'Nariño', 'francisco-pizarro'),
    ('52540', 'Policarpa', 'Nariño', 'policarpa'),
    ('52560', 'Potosí', 'Nariño', 'potosi'),
    ('52565', 'Providencia', 'Nariño', 'providencia-narino'),
    ('52573', 'Puerres', 'Nariño', 'puerres'),
    ('52585', 'Pupiales', 'Nariño', 'pupiales'),
    ('52612', 'Ricaurte', 'Nariño', 'ricaurte-narino'),
    ('52621', 'Roberto Payán', 'Nariño', 'roberto-payan'),
    ('52678', 'Samaniego', 'Nariño', 'samaniego'),
    ('52683', 'Sandoná', 'Nariño', 'sandona'),
    ('52685', 'San Bernardo', 'Nariño', 'san-bernardo-narino'),
    ('52687', 'San Lorenzo', 'Nariño', 'san-lorenzo'),
    ('52693', 'San Pablo', 'Nariño', 'san-pablo-narino'),
    ('52694', 'San Pedro de Cartago', 'Nariño', 'san-pedro-de-cartago'),
    ('52696', 'Santa Bárbara', 'Nariño', 'santa-barbara-narino'),
    ('52699', 'Santacruz', 'Nariño', 'santacruz'),
    ('52720', 'Sapuyes', 'Nariño', 'sapuyes'),
    ('52786', 'Taminango', 'Nariño', 'taminango'),
    ('52788', 'Tangua', 'Nariño', 'tangua'),
    ('52835', 'San Andrés de Tumaco', 'Nariño', 'san-andres-de-tumaco'),
    ('52838', 'Túquerres', 'Nariño', 'tuquerres'),
    ('52885', 'Yacuanquer', 'Nariño', 'yacuanquer'),
    ('54001', 'San José de Cúcuta', 'Norte de Santander', 'san-jose-de-cucuta'),
    ('54003', 'Ábrego', 'Norte de Santander', 'abrego'),
    ('54051', 'Arboledas', 'Norte de Santander', 'arboledas'),
    ('54099', 'Bochalema', 'Norte de Santander', 'bochalema'),
    ('54109', 'Bucarasica', 'Norte de Santander', 'bucarasica'),
    ('54125', 'Cácota', 'Norte de Santander', 'cacota'),
    ('54128', 'Cáchira', 'Norte de Santander', 'cachira'),
    ('54172', 'Chinácota', 'Norte de Santander', 'chinacota'),
    ('54174', 'Chitagá', 'Norte de Santander', 'chitaga'),
    ('54206', 'Convención', 'Norte de Santander', 'convencion'),
    ('54223', 'Cucutilla', 'Norte de Santander', 'cucutilla'),
    ('54239', 'Durania', 'Norte de Santander', 'durania'),
    ('54245', 'El Carmen', 'Norte de Santander', 'el-carmen'),
    ('54250', 'El Tarra', 'Norte de Santander', 'el-tarra'),
    ('54261', 'El Zulia', 'Norte de Santander', 'el-zulia'),
    ('54313', 'Gramalote', 'Norte de Santander', 'gramalote'),
    ('54344', 'Hacarí', 'Norte de Santander', 'hacari'),
    ('54347', 'Herrán', 'Norte de Santander', 'herran'),
    ('54377', 'Labateca', 'Norte de Santander', 'labateca'),
    ('54385', 'La Esperanza', 'Norte de Santander', 'la-esperanza'),
    ('54398', 'La Playa', 'Norte de Santander', 'la-playa'),
    ('54405', 'Los Patios', 'Norte de Santander', 'los-patios'),
    ('54418', 'Lourdes', 'Norte de Santander', 'lourdes'),
    ('54480', 'Mutiscua', 'Norte de Santander', 'mutiscua'),
    ('54498', 'Ocaña', 'Norte de Santander', 'ocana'),
    ('54518', 'Pamplona', 'Norte de Santander', 'pamplona'),
    ('54520', 'Pamplonita', 'Norte de Santander', 'pamplonita'),
    ('54553', 'Puerto Santander', 'Norte de Santander', 'puerto-santander-norte-de-santander'),
    ('54599', 'Ragonvalia', 'Norte de Santander', 'ragonvalia'),
    ('54660', 'Salazar', 'Norte de Santander', 'salazar'),
    ('54670', 'San Calixto', 'Norte de Santander', 'san-calixto'),
    ('54673', 'San Cayetano', 'Norte de Santander', 'san-cayetano-norte-de-santander'),
    ('54680', 'Santiago', 'Norte de Santander', 'santiago-norte-de-santander'),
    ('54720', 'Sardinata', 'Norte de Santander', 'sardinata'),
    ('54743', 'Silos', 'Norte de Santander', 'silos'),
    ('54800', 'Teorama', 'Norte de Santander', 'teorama'),
    ('54810', 'Tibú', 'Norte de Santander', 'tibu'),
    ('54820', 'Toledo', 'Norte de Santander', 'toledo-norte-de-santander'),
    ('54871', 'Villa Caro', 'Norte de Santander', 'villa-caro'),
    ('54874', 'Villa del Rosario', 'Norte de Santander', 'villa-del-rosario'),
    ('63001', 'Armenia', 'Quindío', 'armenia-quindio'),
    ('63111', 'Buenavista', 'Quindío', 'buenavista-quindio'),
    ('63130', 'Calarcá', 'Quindío', 'calarca'),
    ('63190', 'Circasia', 'Quindío', 'circasia'),
    ('63212', 'Córdoba', 'Quindío', 'cordoba-quindio'),
    ('63272', 'Filandia', 'Quindío', 'filandia'),
    ('63302', 'Génova', 'Quindío', 'genova'),
    ('63401', 'La Tebaida', 'Quindío', 'la-tebaida'),
    ('63470', 'Montenegro', 'Quindío', 'montenegro'),
    ('63548', 'Pijao', 'Quindío', 'pijao'),
    ('63594', 'Quimbaya', 'Quindío', 'quimbaya'),
    ('63690', 'Salento', 'Quindío', 'salento'),
    ('66001', 'Pereira', 'Risaralda', 'pereira'),
    ('66045', 'Apía', 'Risaralda', 'apia'),
    ('66075', 'Balboa', 'Risaralda', 'balboa-risaralda'),
    ('66088', 'Belén de Umbría', 'Risaralda', 'belen-de-umbria'),
    ('66170', 'Dosquebradas', 'Risaralda', 'dosquebradas'),
    ('66318', 'Guática', 'Risaralda', 'guatica'),
    ('66383', 'La Celia', 'Risaralda', 'la-celia'),
    ('66400', 'La Virginia', 'Risaralda', 'la-virginia'),
    ('66440', 'Marsella', 'Risaralda', 'marsella'),
    ('66456', 'Mistrató', 'Risaralda', 'mistrato'),
    ('66572', 'Pueblo Rico', 'Risaralda', 'pueblo-rico'),
    ('66594', 'Quinchía', 'Risaralda', 'quinchia'),
    ('66682', 'Santa Rosa de Cabal', 'Risaralda', 'santa-rosa-de-cabal'),
    ('66687', 'Santuario', 'Risaralda', 'santuario'),
    ('68001', 'Bucaramanga', 'Santander', 'bucaramanga'),
    ('68013', 'Aguada', 'Santander', 'aguada'),
    ('68020', 'Albania', 'Santander', 'albania-santander'),
    ('68051', 'Aratoca', 'Santander', 'aratoca'),
    ('68077', 'Barbosa', 'Santander', 'barbosa-santander'),
    ('68079', 'Barichara', 'Santander', 'barichara'),
    ('68081', 'Barrancabermeja', 'Santander', 'barrancabermeja'),
    ('68092', 'Betulia', 'Santander', 'betulia-santander'),
    ('68101', 'Bolívar', 'Santander', 'bolivar-santander'),
    ('68121', 'Cabrera', 'Santander', 'cabrera-santander'),
    ('68132', 'California', 'Santander', 'california'),
    ('68147', 'Capitanejo', 'Santander', 'capitanejo'),
    ('68152', 'Carcasí', 'Santander', 'carcasi'),
    ('68160', 'Cepitá', 'Santander', 'cepita'),
    ('68162', 'Cerrito', 'Santander', 'cerrito'),
    ('68167', 'Charalá', 'Santander', 'charala'),
    ('68169', 'Charta', 'Santander', 'charta'),
    ('68176', 'Chima', 'Santander', 'chima-santander'),
    ('68179', 'Chipatá', 'Santander', 'chipata'),
    ('68190', 'Cimitarra', 'Santander', 'cimitarra'),
    ('68207', 'Concepción', 'Santander', 'concepcion-santander'),
    ('68209', 'Confines', 'Santander', 'confines'),
    ('68211', 'Contratación', 'Santander', 'contratacion'),
    ('68217', 'Coromoro', 'Santander', 'coromoro'),
    ('68229', 'Curití', 'Santander', 'curiti'),
    ('68235', 'El Carmen de Chucurí', 'Santander', 'el-carmen-de-chucuri'),
    ('68245', 'El Guacamayo', 'Santander', 'el-guacamayo'),
    ('68250', 'El Peñón', 'Santander', 'el-penon-santander'),
    ('68255', 'El Playón', 'Santander', 'el-playon'),
    ('68264', 'Encino', 'Santander', 'encino'),
    ('68266', 'Enciso', 'Santander', 'enciso'),
    ('68271', 'Florián', 'Santander', 'florian'),
    ('68276', 'Floridablanca', 'Santander', 'floridablanca'),
    ('68296', 'Galán', 'Santander', 'galan'),
    ('68298', 'Gámbita', 'Santander', 'gambita'),
    ('68307', 'Girón', 'Santander', 'giron'),
    ('68318', 'Guaca', 'Santander', 'guaca'),
    ('68320', 'Guadalupe', 'Santander', 'guadalupe-santander'),
    ('68322', 'Guapotá', 'Santander', 'guapota'),
    ('68324', 'Guavatá', 'Santander', 'guavata'),
    ('68327', 'Güepsa', 'Santander', 'guepsa'),
    ('68344', 'Hato', 'Santander', 'hato'),
    ('68368', 'Jesús María', 'Santander', 'jesus-maria'),
    ('68370', 'Jordán', 'Santander', 'jordan'),
    ('68377', 'La Belleza', 'Santander', 'la-belleza'),
    ('68385', 'Landázuri', 'Santander', 'landazuri'),
    ('68397', 'La Paz', 'Santander', 'la-paz-santander'),
    ('68406', 'Lebrija', 'Santander', 'lebrija'),
    ('68418', 'Los Santos', 'Santander', 'los-santos'),
    ('68425', 'Macaravita', 'Santander', 'macaravita'),
    ('68432', 'Málaga', 'Santander', 'malaga'),
    ('68444', 'Matanza', 'Santander', 'matanza'),
    ('68464', 'Mogotes', 'Santander', 'mogotes'),
    ('68468', 'Molagavita', 'Santander', 'molagavita'),
    ('68498', 'Ocamonte', 'Santander', 'ocamonte'),
    ('68500', 'Oiba', 'Santander', 'oiba'),
    ('68502', 'Onzaga', 'Santander', 'onzaga'),
    ('68522', 'Palmar', 'Santander', 'palmar'),
    ('68524', 'Palmas del Socorro', 'Santander', 'palmas-del-socorro'),
    ('68533', 'Páramo', 'Santander', 'paramo'),
    ('68547', 'Piedecuesta', 'Santander', 'piedecuesta'),
    ('68549', 'Pinchote', 'Santander', 'pinchote'),
    ('68572', 'Puente Nacional', 'Santander', 'puente-nacional'),
    ('68573', 'Puerto Parra', 'Santander', 'puerto-parra'),
    ('68575', 'Puerto Wilches', 'Santander', 'puerto-wilches'),
    ('68615', 'Rionegro', 'Santander', 'rionegro-santander'),
    ('68655', 'Sabana de Torres', 'Santander', 'sabana-de-torres'),
    ('68669', 'San Andrés', 'Santander', 'san-andres-santander'),
    ('68673', 'San Benito', 'Santander', 'san-benito'),
    ('68679', 'San Gil', 'Santander', 'san-gil'),
    ('68682', 'San Joaquín', 'Santander', 'san-joaquin'),
    ('68684', 'San José de Miranda', 'Santander', 'san-jose-de-miranda'),
    ('68686', 'San Miguel', 'Santander', 'san-miguel-santander'),
    ('68689', 'San Vicente de Chucurí', 'Santander', 'san-vicente-de-chucuri'),
    ('68705', 'Santa Bárbara', 'Santander', 'santa-barbara-santander'),
    ('68720', 'Santa Helena del Opón', 'Santander', 'santa-helena-del-opon'),
    ('68745', 'Simacota', 'Santander', 'simacota'),
    ('68755', 'Socorro', 'Santander', 'socorro'),
    ('68770', 'Suaita', 'Santander', 'suaita'),
    ('68773', 'Sucre', 'Santander', 'sucre-santander'),
    ('68780', 'Suratá', 'Santander', 'surata'),
    ('68820', 'Tona', 'Santander', 'tona'),
    ('68855', 'Valle de San José', 'Santander', 'valle-de-san-jose'),
    ('68861', 'Vélez', 'Santander', 'velez'),
    ('68867', 'Vetas', 'Santander', 'vetas'),
    ('68872', 'Villanueva', 'Santander', 'villanueva-santander'),
    ('68895', 'Zapatoca', 'Santander', 'zapatoca'),
    ('70001', 'Sincelejo', 'Sucre', 'sincelejo'),
    ('70110', 'Buenavista', 'Sucre', 'buenavista-sucre'),
    ('70124', 'Caimito', 'Sucre', 'caimito'),
    ('70204', 'Colosó', 'Sucre', 'coloso'),
    ('70215', 'Corozal', 'Sucre', 'corozal'),
    ('70221', 'Coveñas', 'Sucre', 'covenas'),
    ('70230', 'Chalán', 'Sucre', 'chalan'),
    ('70233', 'El Roble', 'Sucre', 'el-roble'),
    ('70235', 'Galeras', 'Sucre', 'galeras'),
    ('70265', 'Guaranda', 'Sucre', 'guaranda'),
    ('70400', 'La Unión', 'Sucre', 'la-union-sucre'),
    ('70418', 'Los Palmitos', 'Sucre', 'los-palmitos'),
    ('70429', 'Majagual', 'Sucre', 'majagual'),
    ('70473', 'Morroa', 'Sucre', 'morroa'),
    ('70508', 'Ovejas', 'Sucre', 'ovejas'),
    ('70523', 'Palmito', 'Sucre', 'palmito'),
    ('70670', 'Sampués', 'Sucre', 'sampues'),
    ('70678', 'San Benito Abad', 'Sucre', 'san-benito-abad'),
    ('70702', 'San Juan de Betulia', 'Sucre', 'san-juan-de-betulia'),
    ('70708', 'San Marcos', 'Sucre', 'san-marcos'),
    ('70713', 'San Onofre', 'Sucre', 'san-onofre'),
    ('70717', 'San Pedro', 'Sucre', 'san-pedro-sucre'),
    ('70742', 'San Luis de Sincé', 'Sucre', 'san-luis-de-since'),
    ('70771', 'Sucre', 'Sucre', 'sucre-sucre'),
    ('70820', 'Santiago de Tolú', 'Sucre', 'santiago-de-tolu'),
    ('70823', 'San José de Toluviejo', 'Sucre', 'san-jose-de-toluviejo'),
    ('73001', 'Ibagué', 'Tolima', 'ibague'),
    ('73024', 'Alpujarra', 'Tolima', 'alpujarra'),
    ('73026', 'Alvarado', 'Tolima', 'alvarado'),
    ('73030', 'Ambalema', 'Tolima', 'ambalema'),
    ('73043', 'Anzoátegui', 'Tolima', 'anzoategui'),
    ('73055', 'Armero', 'Tolima', 'armero'),
    ('73067', 'Ataco', 'Tolima', 'ataco'),
    ('73124', 'Cajamarca', 'Tolima', 'cajamarca'),
    ('73148', 'Carmen de Apicalá', 'Tolima', 'carmen-de-apicala'),
    ('73152', 'Casabianca', 'Tolima', 'casabianca'),
    ('73168', 'Chaparral', 'Tolima', 'chaparral'),
    ('73200', 'Coello', 'Tolima', 'coello'),
    ('73217', 'Coyaima', 'Tolima', 'coyaima'),
    ('73226', 'Cunday', 'Tolima', 'cunday'),
    ('73236', 'Dolores', 'Tolima', 'dolores'),
    ('73268', 'Espinal', 'Tolima', 'espinal'),
    ('73270', 'Falan', 'Tolima', 'falan'),
    ('73275', 'Flandes', 'Tolima', 'flandes'),
    ('73283', 'Fresno', 'Tolima', 'fresno'),
    ('73319', 'Guamo', 'Tolima', 'guamo'),
    ('73347', 'Herveo', 'Tolima', 'herveo'),
    ('73349', 'Honda', 'Tolima', 'honda'),
    ('73352', 'Icononzo', 'Tolima', 'icononzo'),
    ('73408', 'Lérida', 'Tolima', 'lerida'),
    ('73411', 'Líbano', 'Tolima', 'libano'),
    ('73443', 'San Sebastián de Mariquita', 'Tolima', 'san-sebastian-de-mariquita'),
    ('73449', 'Melgar', 'Tolima', 'melgar'),
    ('73461', 'Murillo', 'Tolima', 'murillo'),
    ('73483', 'Natagaima', 'Tolima', 'natagaima'),
    ('73504', 'Ortega', 'Tolima', 'ortega'),
    ('73520', 'Palocabildo', 'Tolima', 'palocabildo'),
    ('73547', 'Piedras', 'Tolima', 'piedras'),
    ('73555', 'Planadas', 'Tolima', 'planadas'),
    ('73563', 'Prado', 'Tolima', 'prado'),
    ('73585', 'Purificación', 'Tolima', 'purificacion'),
    ('73616', 'Rioblanco', 'Tolima', 'rioblanco'),
    ('73622', 'Roncesvalles', 'Tolima', 'roncesvalles'),
    ('73624', 'Rovira', 'Tolima', 'rovira'),
    ('73671', 'Saldaña', 'Tolima', 'saldana'),
    ('73675', 'San Antonio', 'Tolima', 'san-antonio'),
    ('73678', 'San Luis', 'Tolima', 'san-luis-tolima'),
    ('73686', 'Santa Isabel', 'Tolima', 'santa-isabel'),
    ('73770', 'Suárez', 'Tolima', 'suarez-tolima'),
    ('73854', 'Valle de San Juan', 'Tolima', 'valle-de-san-juan'),
    ('73861', 'Venadillo', 'Tolima', 'venadillo'),
    ('73870', 'Villahermosa', 'Tolima', 'villahermosa'),
    ('73873', 'Villarrica', 'Tolima', 'villarrica'),
    ('76001', 'Santiago de Cali', 'Valle del Cauca', 'santiago-de-cali'),
    ('76020', 'Alcalá', 'Valle del Cauca', 'alcala'),
    ('76036', 'Andalucía', 'Valle del Cauca', 'andalucia'),
    ('76041', 'Ansermanuevo', 'Valle del Cauca', 'ansermanuevo'),
    ('76054', 'Argelia', 'Valle del Cauca', 'argelia-valle-del-cauca'),
    ('76100', 'Bolívar', 'Valle del Cauca', 'bolivar-valle-del-cauca'),
    ('76109', 'Buenaventura', 'Valle del Cauca', 'buenaventura'),
    ('76111', 'Guadalajara de Buga', 'Valle del Cauca', 'guadalajara-de-buga'),
    ('76113', 'Bugalagrande', 'Valle del Cauca', 'bugalagrande'),
    ('76122', 'Caicedonia', 'Valle del Cauca', 'caicedonia'),
    ('76126', 'Calima', 'Valle del Cauca', 'calima'),
    ('76130', 'Candelaria', 'Valle del Cauca', 'candelaria-valle-del-cauca'),
    ('76147', 'Cartago', 'Valle del Cauca', 'cartago'),
    ('76233', 'Dagua', 'Valle del Cauca', 'dagua'),
    ('76243', 'El Águila', 'Valle del Cauca', 'el-aguila'),
    ('76246', 'El Cairo', 'Valle del Cauca', 'el-cairo'),
    ('76248', 'El Cerrito', 'Valle del Cauca', 'el-cerrito'),
    ('76250', 'El Dovio', 'Valle del Cauca', 'el-dovio'),
    ('76275', 'Florida', 'Valle del Cauca', 'florida'),
    ('76306', 'Ginebra', 'Valle del Cauca', 'ginebra'),
    ('76318', 'Guacarí', 'Valle del Cauca', 'guacari'),
    ('76364', 'Jamundí', 'Valle del Cauca', 'jamundi'),
    ('76377', 'La Cumbre', 'Valle del Cauca', 'la-cumbre'),
    ('76400', 'La Unión', 'Valle del Cauca', 'la-union-valle-del-cauca'),
    ('76403', 'La Victoria', 'Valle del Cauca', 'la-victoria-valle-del-cauca'),
    ('76497', 'Obando', 'Valle del Cauca', 'obando'),
    ('76520', 'Palmira', 'Valle del Cauca', 'palmira'),
    ('76563', 'Pradera', 'Valle del Cauca', 'pradera'),
    ('76606', 'Restrepo', 'Valle del Cauca', 'restrepo-valle-del-cauca'),
    ('76616', 'Riofrío', 'Valle del Cauca', 'riofrio'),
    ('76622', 'Roldanillo', 'Valle del Cauca', 'roldanillo'),
    ('76670', 'San Pedro', 'Valle del Cauca', 'san-pedro-valle-del-cauca'),
    ('76736', 'Sevilla', 'Valle del Cauca', 'sevilla'),
    ('76823', 'Toro', 'Valle del Cauca', 'toro'),
    ('76828', 'Trujillo', 'Valle del Cauca', 'trujillo'),
    ('76834', 'Tuluá', 'Valle del Cauca', 'tulua'),
    ('76845', 'Ulloa', 'Valle del Cauca', 'ulloa'),
    ('76863', 'Versalles', 'Valle del Cauca', 'versalles'),
    ('76869', 'Vijes', 'Valle del Cauca', 'vijes'),
    ('76890', 'Yotoco', 'Valle del Cauca', 'yotoco'),
    ('76892', 'Yumbo', 'Valle del Cauca', 'yumbo'),
    ('76895', 'Zarzal', 'Valle del Cauca', 'zarzal'),
    ('81001', 'Arauca', 'Arauca', 'arauca'),
    ('81065', 'Arauquita', 'Arauca', 'arauquita'),
    ('81220', 'Cravo Norte', 'Arauca', 'cravo-norte'),
    ('81300', 'Fortul', 'Arauca', 'fortul'),
    ('81591', 'Puerto Rondón', 'Arauca', 'puerto-rondon'),
    ('81736', 'Saravena', 'Arauca', 'saravena'),
    ('81794', 'Tame', 'Arauca', 'tame'),
    ('85001', 'Yopal', 'Casanare', 'yopal'),
    ('85010', 'Aguazul', 'Casanare', 'aguazul'),
    ('85015', 'Chámeza', 'Casanare', 'chameza'),
    ('85125', 'Hato Corozal', 'Casanare', 'hato-corozal'),
    ('85136', 'La Salina', 'Casanare', 'la-salina'),
    ('85139', 'Maní', 'Casanare', 'mani'),
    ('85162', 'Monterrey', 'Casanare', 'monterrey'),
    ('85225', 'Nunchía', 'Casanare', 'nunchia'),
    ('85230', 'Orocué', 'Casanare', 'orocue'),
    ('85250', 'Paz de Ariporo', 'Casanare', 'paz-de-ariporo'),
    ('85263', 'Pore', 'Casanare', 'pore'),
    ('85279', 'Recetor', 'Casanare', 'recetor'),
    ('85300', 'Sabanalarga', 'Casanare', 'sabanalarga-casanare'),
    ('85315', 'Sácama', 'Casanare', 'sacama'),
    ('85325', 'San Luis de Palenque', 'Casanare', 'san-luis-de-palenque'),
    ('85400', 'Támara', 'Casanare', 'tamara'),
    ('85410', 'Tauramena', 'Casanare', 'tauramena'),
    ('85430', 'Trinidad', 'Casanare', 'trinidad'),
    ('85440', 'Villanueva', 'Casanare', 'villanueva-casanare'),
    ('86001', 'Mocoa', 'Putumayo', 'mocoa'),
    ('86219', 'Colón', 'Putumayo', 'colon-putumayo'),
    ('86320', 'Orito', 'Putumayo', 'orito'),
    ('86568', 'Puerto Asís', 'Putumayo', 'puerto-asis'),
    ('86569', 'Puerto Caicedo', 'Putumayo', 'puerto-caicedo'),
    ('86571', 'Puerto Guzmán', 'Putumayo', 'puerto-guzman'),
    ('86573', 'Puerto Leguízamo', 'Putumayo', 'puerto-leguizamo'),
    ('86749', 'Sibundoy', 'Putumayo', 'sibundoy'),
    ('86755', 'San Francisco', 'Putumayo', 'san-francisco-putumayo'),
    ('86757', 'San Miguel', 'Putumayo', 'san-miguel-putumayo'),
    ('86760', 'Santiago', 'Putumayo', 'santiago-putumayo'),
    ('86865', 'Valle del Guamuez', 'Putumayo', 'valle-del-guamuez'),
    ('86885', 'Villagarzón', 'Putumayo', 'villagarzon'),
    ('88001', 'San Andrés', 'Archipiélago de San Andrés, Providencia y Santa Catalina', 'san-andres-san-andres'),
    ('88564', 'Providencia', 'Archipiélago de San Andrés, Providencia y Santa Catalina', 'providencia-san-andres'),
    ('91001', 'Leticia', 'Amazonas', 'leticia'),
    ('91263', 'El Encanto', 'Amazonas', 'el-encanto'),
    ('91405', 'La Chorrera', 'Amazonas', 'la-chorrera'),
    ('91407', 'La Pedrera', 'Amazonas', 'la-pedrera'),
    ('91430', 'La Victoria', 'Amazonas', 'la-victoria-amazonas'),
    ('91460', 'Mirití - Paraná', 'Amazonas', 'miriti-parana'),
    ('91530', 'Puerto Alegría', 'Amazonas', 'puerto-alegria'),
    ('91536', 'Puerto Arica', 'Amazonas', 'puerto-arica'),
    ('91540', 'Puerto Nariño', 'Amazonas', 'puerto-narino'),
    ('91669', 'Puerto Santander', 'Amazonas', 'puerto-santander-amazonas'),
    ('91798', 'Tarapacá', 'Amazonas', 'tarapaca'),
    ('94001', 'Inírida', 'Guainía', 'inirida'),
    ('94343', 'Barrancominas', 'Guainía', 'barrancominas'),
    ('94883', 'San Felipe', 'Guainía', 'san-felipe'),
    ('94884', 'Puerto Colombia', 'Guainía', 'puerto-colombia-guainia'),
    ('94885', 'La Guadalupe', 'Guainía', 'la-guadalupe'),
    ('94886', 'Cacahual', 'Guainía', 'cacahual'),
    ('94887', 'Pana Pana', 'Guainía', 'pana-pana'),
    ('94888', 'Morichal', 'Guainía', 'morichal'),
    ('95001', 'San José del Guaviare', 'Guaviare', 'san-jose-del-guaviare'),
    ('95015', 'Calamar', 'Guaviare', 'calamar-guaviare'),
    ('95025', 'El Retorno', 'Guaviare', 'el-retorno'),
    ('95200', 'Miraflores', 'Guaviare', 'miraflores-guaviare'),
    ('97001', 'Mitú', 'Vaupés', 'mitu'),
    ('97161', 'Carurú', 'Vaupés', 'caruru'),
    ('97511', 'Pacoa', 'Vaupés', 'pacoa'),
    ('97666', 'Taraira', 'Vaupés', 'taraira'),
    ('97777', 'Papunahua', 'Vaupés', 'papunahua'),
    ('97889', 'Yavaraté', 'Vaupés', 'yavarate'),
    ('99001', 'Puerto Carreño', 'Vichada', 'puerto-carreno'),
    ('99524', 'La Primavera', 'Vichada', 'la-primavera'),
    ('99624', 'Santa Rosalía', 'Vichada', 'santa-rosalia'),
    ('99773', 'Cumaribo', 'Vichada', 'cumaribo')
),
completar as (
  update cities c
  set dane_code = d.dane_code, department = d.department
  from divipola d
  where c.slug = d.slug and c.dane_code is null
  returning c.id
)
insert into cities (dane_code, name, department, slug)
select dane_code, name, department, slug from divipola
on conflict do nothing;

-- Búsqueda del combobox ("medellin" sin tilde, subcadenas).
create index if not exists cities_name_trgm
  on cities using gin (public.f_unaccent(lower(name)) extensions.gin_trgm_ops);
